# git-cliff configuration
# https://git-cliff.org/docs/configuration

[bump]
features_always_bump_minor = true
breaking_always_bump_major = true

[changelog]
header = """
# Changelog\n
"""
body = """
{%- if version %}
## {{ version | trim_start_matches(pat="v") }} - {{ timestamp | date(format="%Y-%m-%d") }}
{%- else %}
## Unreleased
{%- endif %}
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | striptags | trim | upper_first }}
{% for commit in commits %}
    - {% if commit.scope %}*({{ commit.scope }})* {% endif %}{{ commit.message | split(pat="\n") | first | upper_first | trim }}\
{% endfor %}
{% endfor %}\n
"""
trim = true

[git]
conventional_commits = true
filter_unconventional = false
split_commits = false
tag_pattern = "v[0-9].*"
sort_commits = "oldest"
commit_parsers = [
    { message = "^chore\\(release\\)", skip = true },
    { message = "^Merge", skip = true },
    { message = "^Bump ", skip = true },
    { message = "^Cut a release", skip = true },
    { message = "(?i)(^format|update).*change.?log", skip = true },
    { message = "^feat", group = "Added" },
    { message = "^fix", group = "Fixed" },
    { message = "^perf", group = "Changed" },
    { message = "^refactor", group = "Changed" },
    { message = "^docs", group = "Changed" },
    { message = "^style", group = "Changed" },
    { message = "^build", group = "Changed" },
    { message = "^ci", group = "Changed" },
    { message = "^chore", group = "Changed" },
    { message = "^test", group = "Changed" },
    { message = "^revert", group = "Removed" },
    { message = "^[aA]dd", group = "Added" },
    { message = "^[rR]emove", group = "Removed" },
    { message = "^.*", group = "Changed" },
]
protect_breaking_commits = false
filter_commits = false
topo_order = false
