name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - uses: actions/setup-go@v3
        with:
          go-version: "~1.19.0"
      - name: Install bats-core
        run: |
          git clone --depth 1 --branch v1.7.0 https://github.com/bats-core/bats-core.git $HOME/bats-core
          echo "$HOME/bats-core/bin" >>"$GITHUB_PATH"
      - run: make dev-install test-all
